version: '3.8'

services:
  fastapi:
    build: .
    container_name: fastapi-container
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis-container
    ports:
      - "6379:6379"
